### ISSUE TITLE
ESM Build Missing

### ISSUE THREAD

**Issue by jceb** [digitalbazaar/security-context#4]
I tried importing module `@digitalbazaar/ed25519-signature-2020` via the esm.sh CDN from deno and it runs into an error. When I open the [CDN link](https://esm.sh/v121/@digitalbazaar/security-context@1.0.0) in the browser it shows the error that file `dist/context.esm.js` is missing. The issue is visible on the npm package as well when I navigate into the `dist/` folder: https://www.npmjs.com/package/@digitalbazaar/security-context?activeTab=code

Could you republish the package and include the missing file?

**Comment by arty-name** [comment]
We see the same error when trying to use `@digitalbazaar/security-context` in an ESM application

**Comment by davidlehn** [comment]
I'm surprised this wasn't caught earlier.  The file was built but not included in the npm package.  I guess most paths to this package are using CJS.  Fixed in 1.0.1.  I did a basic local test and it looks like proper symbols are being exported.  If more complex use cases fail, please file another issue.  Thanks.

**Comment by arty-name** [comment]
Thank you for the very quick response!

**Comment by davidlehn** [comment]
It wasn't that quick... I totally missed the original report, oops!

**Comment by arty-name** [comment]
Happens to the best of us…
